- name: change systemd cgroup driver to default cgroupfs
  replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = true'
    replace: 'SystemdCgroup = false'

- name: Restart containerd service
  systemd:
    name: containerd
    state: restarted

- name: Install prereq packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - git
      - make
      - gcc

- name: Capture the commit ID
  set_fact:
    commit: "{{ build_version | regex_search('(?<=\\+)(.*)') }}"

- name: Clone a kubernetes github repo
  git:
    repo: https://github.com/kubernetes/kubernetes
    dest: /kubernetes/
    version: "{{ commit }}"
    clone: yes
    update: yes

- name: Create a shell script
  copy:
    content: |
      #!/bin/bash
      set -o errexit

      focus=${FOCUS:-"\[NodeConformance\]"}
      skip=${SKIP-"\[Flaky\]|\[Slow\]|\[Serial\]"}
      echo 'This is a script to run e2e-node tests'
      pushd /kubernetes
        make test-e2e-node FOCUS=${focus} SKIP=${skip}
      popd
    dest: /make-test-e2e-node.sh
    mode: '0755'
