---
- name: Install CRI-O and dependencies.
  yum:
    name:
      - conmon
    state: present
    disable_gpg_check: true

- name: Download CRI-O - {{ crio_version }}
  unarchive:
    src: "https://storage.googleapis.com/cri-o/artifacts/cri-o.ppc64le.v{{ crio_version }}.tar.gz"
    dest: "/usr/local/bin/"
    remote_src: yes
    include: cri-o/bin
    extra_opts:
      - --strip-components=2
  retries: 3
  delay: 5

- name: Create /etc/containers dir.
  file:
    path: /etc/containers
    state: directory
    mode: '0755'

# Reference: https://github.com/containers/image/blob/main/docs/containers-policy.json.5.md
# for policy refinement from the current "insecureAcceptAnything".
- name: Define container pull policies on nodes.
  copy:
    src: crio/policy.json
    dest: /etc/containers
    mode: '0644'

- name: Create a /etc/crio dir
  file:
    path: /etc/crio
    state: directory
    mode: '0755'

- name: Generate crio.conf file
  template:
    src: crio/crio.conf.j2
    dest:  /etc/crio/crio.conf
    mode: '0644'

- name: Create the crio.service file on nodes.
  copy:
    src:  crio/crio.service
    dest: /usr/lib/systemd/system/crio.service
    mode: '0644'

# TODO: Validate if the file needs to be created once when installations are possible.
- name: Create /var/lib/crio/clean.shutdown file.
  shell: mkdir -p /var/lib/crio && touch /var/lib/crio/clean.shutdown

- name: Enable and Restart crio.
  systemd:
    name: crio
    state: restarted
    enabled: yes
